"""Added remaining tables for v1

Revision ID: 236b407e0c0e
Revises: a7bc4d8879f3
Create Date: 2023-03-27 13:23:32.611260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '236b407e0c0e'
down_revision = 'a7bc4d8879f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
