"""Added email_sent and response to invitation table

Revision ID: 6979d53754f5
Revises: 6bb307a7feab
Create Date: 2023-03-27 13:33:44.641215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6979d53754f5'
down_revision = '6bb307a7feab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('response', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'response')
    # ### end Alembic commands ###
