"""Added contact id to invitation table

Revision ID: a3c6af7cfc26
Revises: b06aebd7c249
Create Date: 2023-03-27 13:30:05.116072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c6af7cfc26'
down_revision = 'b06aebd7c249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invitations', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'contact_id')
    # ### end Alembic commands ###
