"""Made some fields optional

Revision ID: b373d86be53e
Revises: b240cd07c411
Create Date: 2023-03-28 00:06:45.801025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b373d86be53e'
down_revision = 'b240cd07c411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('contacts', 'phone_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('contacts', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
