"""owner required for contact

Revision ID: c03ee20ea584
Revises: 0d51ad070e03
Create Date: 2023-03-28 22:17:36.877495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03ee20ea584'
down_revision = '0d51ad070e03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('owner_email', sa.String(length=200), nullable=False))
    op.create_foreign_key(None, 'contacts', 'users', ['owner_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'owner_email')
    # ### end Alembic commands ###
